config/routes.rb
SchoolManagementSystem::Application.routes.draw do
  get "alerts/quick_sms"

  get "alerts/noticeboard"

  resources :non_teaching_staffs

  resources :teaching_staffs

  resources :students

  get "wishes/index"
  get "users/new"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  resources :sessions

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  post "alerts/send_message"
  post "alerts/send_multi_message"

  
  get "home/index"
  get "home/account"
  post "home/user_profile"
  post "home/settings"

  root :to => 'home#index'

end

app/models/non_teaching_staff.rb
class NonTeachingStaff < ActiveRecord::Base
  attr_accessible :full_name, :father_name, :date_of_birth, :date_of_joining, :married,
                  :email, :address, :mobile, :spouse_name, :qualification, :role, :aniversary_date

  def self.search(query)
    where("full_name like ?", "%#{query}%") 
  end

  def birthday_date
    date_of_birth.strftime("%d/%m")
  end

  def job_anniversary
    date_of_joining.strftime("%d/%m")
  end

  def wedding_anniversary
    aniversary_date.strftime("%d/%m")
  end

  def self.fetch_birthday
    birthday = []
    self.all.each do |non_teacher|
      if(non_teacher.birthday_date == "#{Date.today.day}/#{Date.today.month}")
        birthday << non_teacher 
      end
    end
    return birthday
  end

  def self.fetch_job_anniversary
    job_anniversary = []
    self.all.each do |non_teacher|
      if(non_teacher.job_anniversary == "#{Date.today.day}/#{Date.today.month}")
        job_anniversary << non_teacher 
      end
    end
    return job_anniversary
  end

  def self.fetch_wedding_anniversary
    wedding_anniversary = []
    self.all.each do |non_teacher|
      if(non_teacher.wedding_anniversary == "#{Date.today.day}/#{Date.today.month}")
        wedding_anniversary << non_teacher 
      end
    end
    return wedding_anniversary
  end  

end

app/controllers/non_teaching_staffs_controller.rb
class NonTeachingStaffsController < ApplicationController
  before_filter :authenticate

  def index
    if params[:search]
      @non_teaching_staffs = NonTeachingStaff.search(params[:search])
                         .paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
    else
      @non_teaching_staffs = NonTeachingStaff.paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
    end    
  end
  
  def new
    @non_teaching_staff = NonTeachingStaff.new
  end

  def create
    @non_teaching_staff = NonTeachingStaff.new(params[:teaching_staff])
    if @non_teaching_staff.save
      flash[:notice] = "Saved"
      redirect_to non_teaching_staffs_path
    else
      flash[:notice] = "Error"
    end
  end

  def show
    @non_teaching_staff = NonTeachingStaff.find(params[:id])
  end

  def destroy
    @non_teaching_staff = NonTeachingStaff.find(params[:id])
    @non_teaching_staff.destroy
    redirect_to non_teaching_staffs_path
  end
end

app/views/non_teaching_staffs/_form.html.erb
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
  <div class="content">
    <div id="container">
      <!-- BEGIN BASIC FORM ELEMENTS-->
      <div class="row-fluid">
        <%= form_for @non_teaching_staff, :html => {:style=>"margin-top:20px"}  do |f| %>
          <% if @non_teaching_staff.errors.any? %>
            <div class="alert">
              <button class="close" data-dismiss="alert"></button>
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @non_teaching_staff.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
            </div>
          <% end %>
          <div class="span10">
            <div class="grid simple">
              <div class="grid-title no-border">
                <h4>Add new Non Teaching Staff</h4>
              </div>
              <div class="grid-body no-border"> <br>
                <div class="row-fluid">
                  <div class="span8">
                    <div class="control-group">
                      <label class="control-label">Full Name</label>
                      <span class="help">e.g. "Senthil Kumar"</span>
                      <div class="controls">
                        <%= f.text_field :full_name, :class=>"span12", :placeholder => "Staff Name"  %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Father Name</label>
                      <span class="help">e.g. "Bhaskaran"</span>
                      <div class="controls">
                        <%= f.text_field :father_name, :class=>"span12", :placeholder => "Father Name"  %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Date of Birth</label>
                      <span class="help">e.g. "17/11/1986"</span>
                      <div class="controls">
                        <div class="input-append success date span12">
                          <%= f.text_field :date_of_birth, :class=>"span12",  :value =>  @non_teaching_staff.date_of_birth.blank? ? Date.today.strftime("%d/%m/%Y") : @non_teaching_staff.date_of_birth %>
                          <span class="add-on"><span class="arrow"></span>
                          <i class="icon-th"></i></span> </div>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Date of Joining</label>
                      <span class="help">e.g. "17/11/1986"</span>
                      <div class="controls">
                        <div class="input-append success date span12">
                          <%= f.text_field :date_of_joining, :class=>"span12", :placeholder => "Father Name", :value =>  @non_teaching_staff.date_of_joining.blank? ? Date.today.strftime("%d/%m/%Y") : @non_teaching_staff.date_of_joining %>
                          <span class="add-on"><span class="arrow"></span>
                          <i class="icon-th"></i></span> </div>
                      </div>
                    </div> 
                    <div class="control-group">
                      <label class="control-label">Qualification</label>
                      <span class="help">e.g. "B.Tech"</span>
                      <div class="controls">
                        <%= f.text_field :qualification, :class=>"span12", :placeholder => "Qualification"  %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Role</label>
                      <span class="help">e.g. "Mathematics Teacher"</span>
                      <div class="controls">
                        <%= f.text_field :role, :class=>"span12", :placeholder => "Role"  %>
                      </div>
                    </div>                   
                    <div class="control-group">
                      <label class="control-label">Married</label>
                      <span class="help">e.g. "Yes"</span>
                      <div class="controls">
                        <div class="checkbox check-success  ">
                          <%= f.check_box :married, :class=>"span12", :id => "checkbox2" %>
                          <label for="checkbox2">Yes</label>
                        </div>
                      </div>
                    </div>   
                    <div class="control-group">
                      <label class="control-label">Spouse Name</label>
                      <span class="help">e.g. "Spouse Name"</span>
                      <div class="controls">
                        <%= f.text_field :spouse_name, :class=>"span12", :placeholder => "Spouse Name"  %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Anniversary Date</label>
                      <span class="help">e.g. "17/11/1986"</span>
                      <div class="controls">
                        <div class="input-append success date span12">
                          <%= f.text_field :aniversary_date, :class=>"span12", :value =>  @non_teaching_staff.aniversary_date.blank? ? Date.today.strftime("%d/%m/%Y") : @non_teaching_staff.aniversary_date %>
                          <span class="add-on"><span class="arrow"></span>
                          <i class="icon-th"></i></span> </div>
                      </div>
                    </div> 
                    <div class="control-group">
                      <label class="control-label">Mobile Number</label>
                      <span class="help">e.g. "987654321"</span>
                      <div class="controls">
                        <%= f.text_field :mobile, :class=>"span12", :placeholder => "Mobile Number"  %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Email</label>
                      <span class="help">e.g. "test@example.com"</span>
                      <div class="controls">
                        <%= f.text_field :email, :class=>"span12", :placeholder => "Email"  %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Address</label>
                      <span class="help">e.g. "123, 2nd street, Pondicherry"</span>
                      <div class="controls">
                        <%= f.text_area :address, :class=>"span12", :placeholder => "Address", :rows => "10"  %>
                      </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Create Non Teacher</button>
                    <a href="#" class="btn btn-primary">Clear</a>
                    <a href="<%= students_path %>" class="btn btn-primary">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/non_teaching_staffs/edit.html.erb
<h1>Editing teaching_staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @teaching_staff %> |
<%= link_to 'Back', teaching_staffs_path %>

app/views/non_teaching_staffs/index.html.erb
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
  <div class="content">
    <div id="container">
      <div class="row-fluid">
        <div class="span12">
          <div class="grid simple ">
            <div class="grid-title">
              <h4>Listing <span class="semi-bold">Non Teachers</span></h4>
              <div class="tools"> 
                <a href="javascript:;" class="collapse"></a>
                <a href="javascript:;" class="reload"></a>
              </div>
            </div>
            
            <div class="grid-body ">
              <div class="row-fluid">
                <table class="table table-hover table-condensed" id="example">
                  <%= form_tag(non_teaching_staffs_path, :method => "get", id: "search-form") do %>
                    <div class="input-prepend inside search-form no-boarder"  style="float: right;">
                      <span class="add-on"> 
                        <a href="#" class="" >
                          <div class="iconset top-search"></div>
                        </a>
                      </span>
                      <%= text_field_tag :search, params[:search], placeholder: "Search Non Teacher", :class=>"no-boarder"%>
                    </div>
                  <% end %>
                  <thead>
                    <tr>
                      <th width="10%">Full Name</th>
                      <th width="10%" data-hide="phone,tablet">Father name</th>
                      <th width="10%" data-hide="phone,tablet">Role</th>
                      <th width="10%" data-hide="phone,tablet">Phone number</th>
                      <th width="10%" data-hide="phone,tablet">Email</th>
                      <th width="10%" data-hide="phone,tablet">Address</th>
                      <th width="6%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @non_teaching_staffs.each do |non_teaching_staff| %>
                      <tr >
                        <td valign="middle"><%= non_teaching_staff.full_name %></td>
                        <td valign="middle"><span class="muted"><%= non_teaching_staff.father_name %></span></td>
                        <td valign="middle"><span class="muted"><%= non_teaching_staff.role %></span></td>
                        <td valign="middle"><span class="muted"><%= non_teaching_staff.mobile %></span></td>
                        <td valign="middle"><span class="muted"><%= non_teaching_staff.email %></span></td>
                        <td valign="middle"><span class="muted"><%= non_teaching_staff.address %></span></td>
                        <td valign="middle">
                          <%= link_to 'Edit', edit_non_teaching_staff_path(non_teaching_staff) %>
                          <%= link_to 'Delete', non_teaching_staff, method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <%= will_paginate @non_teaching_staffs %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/non_teaching_staffs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', teaching_staffs_path %>

app/views/non_teaching_staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @teaching_staff.full_name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @teaching_staff.father_name %>
</p>

<p>
  <strong>Date of joining:</strong>
  <%= @teaching_staff.date_of_joining %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @teaching_staff.date_of_birth %>
</p>

<p>
  <strong>Married:</strong>
  <%= @teaching_staff.married %>
</p>

<p>
  <strong>Spouse name:</strong>
  <%= @teaching_staff.spouse_name %>
</p>

<p>
  <strong>Aniversary date:</strong>
  <%= @teaching_staff.aniversary_date %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @teaching_staff.qualification %>
</p>

<p>
  <strong>Role:</strong>
  <%= @teaching_staff.role %>
</p>

<%= link_to 'Edit', edit_teaching_staff_path(@teaching_staff) %> |
<%= link_to 'Back', teaching_staffs_path %>