config/routes.rb
SchoolManagementSystem::Application.routes.draw do
  get "alerts/quick_sms"

  get "alerts/noticeboard"

  resources :non_teaching_staffs

  resources :teaching_staffs

  resources :students

  get "wishes/index"
  get "users/new"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  resources :sessions

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  post "alerts/send_message"
  post "alerts/send_multi_message"

  
  get "home/index"
  get "home/account"
  post "home/user_profile"
  post "home/settings"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate
  def index
    @students = Student.all
    @last_student = Student.last
    @teachers = TeachingStaff.all
    @last_teacher = TeachingStaff.last
    @non_teachers = NonTeachingStaff.all
    @last_non_teacher = NonTeachingStaff.last
    @sms = Sms.all
    @last_sms = Sms.last

    #Birthday
    @birthday_name = []
    @birthday_phone_number = []
    @birthday_role = []
    today = Date.today.strftime("%d/%m/%Y")
    # student_birthdays = Student.find_all_by_dob(today)
    # student_birthdays = Student.where(["DAY(dob) = ? AND MONTH(dob) = ?", Date.today.day, Date.today.month])
    student_birthdays = Student.fetch_birthday
    student_birthdays.each do |student_birthday|
      @birthday_name << student_birthday.name
      @birthday_phone_number << student_birthday.phone_number
      @birthday_role << "Class : " + student_birthday.standard + " - " + student_birthday.section
    end

    # teachers_birthdays = TeachingStaff.where(["DAY(date_of_birth) = ? AND MONTH(date_of_birth) = ?", 
    #                                     Date.today.day, Date.today.month])

    teachers_birthdays = TeachingStaff.fetch_birthday
    teachers_birthdays.each do |teachers_birthday|
      @birthday_name << teachers_birthday.full_name
      @birthday_phone_number << teachers_birthday.mobile
      @birthday_role << teachers_birthday.role
    end

    # non_teachers_birthdays = NonTeachingStaff.where(["DAY(date_of_birth) = ? AND MONTH(date_of_birth) = ?", 
                                        # Date.today.day, Date.today.month])
    non_teachers_birthdays = NonTeachingStaff.fetch_birthday
    non_teachers_birthdays.each do |non_teachers_birthday|
      @birthday_name << non_teachers_birthday.full_name
      @birthday_phone_number << non_teachers_birthday.mobile
      @birthday_role << non_teachers_birthday.role
    end

    # Job anniversary
    @job_anniversary_name = []
    @job_anniversary_phone_number = []
    @job_anniversary_role = []

    teachers_job_anniversaries = TeachingStaff.fetch_job_anniversary
    # teachers_job_anniversaries = TeachingStaff.where(["DAY(date_of_joining) = ? AND MONTH(date_of_joining) = ?", 
    #                                     Date.today.day, Date.today.month])
    teachers_job_anniversaries.each do |teachers_job_anniversary|
      @job_anniversary_name << teachers_job_anniversary.full_name
      @job_anniversary_phone_number << teachers_job_anniversary.mobile
      @job_anniversary_role << teachers_job_anniversary.role
    end

    non_teachers_job_anniversaries = NonTeachingStaff.fetch_job_anniversary
    # non_teachers_job_anniversaries = NonTeachingStaff.where(["DAY(date_of_joining) = ? AND MONTH(date_of_joining) = ?", 
    #                                     Date.today.day, Date.today.month])
    non_teachers_job_anniversaries.each do |non_teachers_job_anniversary|
      @job_anniversary_name << non_teachers_job_anniversary.full_name
      @job_anniversary_phone_number << non_teachers_job_anniversary.mobile
      @job_anniversary_role << non_teachers_job_anniversary.role
    end

    # Wedding anniversary
    @wedding_anniversary_name = []
    @wedding_anniversary_phone_number = []
    @wedding_anniversary_role = []

    teachers_wedding_anniversaries = TeachingStaff.fetch_wedding_anniversary
    # teachers_wedding_anniversaries = TeachingStaff.where(["DAY(aniversary_date) = ? AND MONTH(aniversary_date) = ?", 
    #                                     Date.today.day, Date.today.month])
    teachers_wedding_anniversaries.each do |teachers_wedding_anniversary|
      @wedding_anniversary_name << teachers_wedding_anniversary.full_name
      @wedding_anniversary_phone_number << teachers_wedding_anniversary.mobile
      @wedding_anniversary_role << teachers_wedding_anniversary.role
    end


    non_teachers_wedding_anniversaries = NonTeachingStaff.fetch_wedding_anniversary
    # non_teachers_wedding_anniversaries = NonTeachingStaff.where(["DAY(aniversary_date) = ? AND MONTH(aniversary_date) = ?", 
    #                                     Date.today.day, Date.today.month])
    non_teachers_wedding_anniversaries.each do |non_teachers_wedding_anniversary|
      @wedding_anniversary_name << non_teachers_wedding_anniversary.full_name
      @wedding_anniversary_phone_number << non_teachers_wedding_anniversary.mobile
      @wedding_anniversary_role << non_teachers_wedding_anniversary.role
    end
  end

  def account
    @user = User.find(current_user.id)
    @setting = Settings.first
    @setting = Settings.new if @setting.blank?
  end

  def user_profile
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:users])
      flash[:notice] = "Success"
      redirect_to home_account_path
    else
      render home_account_path
    end
  end

  def settings
    @settings = Settings.find_or_initialize_by_username(params[:settings][:username])
    if @settings.update_attributes(params[:settings])
      flash[:notice] = "Success"
      redirect_to home_account_path
    else
      render home_account_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/account.html.erb
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
  <div class="content">  
    <div class="page-title">  
      <h3>Account Page</h3>   
    </div>
    <div id="container">
      <div class="span6">
        <div class="grid simple">
          <div class="grid-title">
            <h4>User <span class="semi-bold">Profile</span></h4>
            <div class="tools"> 
              <a href="javascript:;" class="collapse"></a>
              <a href="javascript:;" class="reload"></a>
            </div>
          </div>
          <div class="grid-body ">
            <div class="row-fluid">
              <%= form_tag home_user_profile_path  do %>
                <% if @user.errors.any? %>
                  <div class="alert">
                    <button class="close" data-dismiss="alert"></button>
                  <h2>Form is invalid</h2>
                  <ul>
                    <% for message in @user.errors.full_messages %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                  </div>
                <% end %>
                <div class="span8">
                  <div class="control-group">
                    <label class="control-label">User Name</label>
                    <span class="help">e.g. "senthil"</span>
                    <div class="controls">
                      <input type="text" name="users[username]" class="span12" value = "<%= @user.username %>" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Full Name</label>
                    <span class="help">e.g. "Senthil Kumar Bhaskaran"</span>
                    <div class="controls">
                      <input type="text" name="users[fullname]" class="span12" value="<%= @user.fullname %>" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Email</label>
                    <span class="help">e.g. "senthil@example.com"</span>
                    <div class="controls">
                      <input type="text" name="users[email]" class="span12" value="<%= @user.email %>" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Password</label>
                    <span class="help">e.g. "****"</span>
                    <div class="controls">
                      <input type="password" name="users[password]" class="span12" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Password Confirmation</label>
                    <span class="help">e.g. "****"</span>
                    <div class="controls">
                      <input type="password" name="users[password_confirmation]" class="span12" />
                    </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Update</button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="grid simple">
          <div class="grid-title">
            <h4>Settings <span class="semi-bold">Profile</span></h4>
            <div class="tools"> 
              <a href="javascript:;" class="collapse"></a>
              <a href="javascript:;" class="reload"></a>
            </div>
          </div>
          <div class="grid-body ">
            <div class="row-fluid">
              <%= form_tag home_settings_path  do %>
                <% if @setting.errors.any? %>
                  <div class="alert">
                    <button class="close" data-dismiss="alert"></button>
                    <h2>Form is invalid</h2>
                    <ul>
                      <% for message in @setting.errors.full_messages %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <div class="span8">
                  <div class="control-group">
                    <label class="control-label">User Name</label>
                    <span class="help">e.g. "senthil"</span>
                    <div class="controls">
                      <input type="text" name="settings[username]" class="span12" value="<%= @setting.username %> "/>
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Password</label>
                    <span class="help">e.g. "******"</span>
                    <div class="controls">
                      <input type="text" name="settings[password]" class="span12" value="<%= @setting.password %>" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Signature</label>
                    <span class="help">e.g. "School Name"</span>
                    <div class="controls">
                      <input type="text" name="settings[signature]" class="span12" value="<%= @setting.signature %>" />
                    </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Update</button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
  <div class="content">  
    <div class="page-title">  
      <h3>Dashboard </h3>   
    </div>
    <div id="container">
      <div class="row-fluid spacing-bottom 2col"> 
        <div class="span3 ">  
          <div class="tiles blue added-margin">
            <div class="tiles-body">
              <div class="controller">            
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>    
              </div>    
              <div class="tiles-title">
                TOTAL SMS SENT
              </div> 
              <div class="heading">
                <span class="animate-number" data-value="<%= @sms.count %>" data-animation-duration="1000"><%= @sms.count %></span>  
              </div>
              <div class="progress transparent progress-white progress-small no-radius">
                <div class="bar animate-progress-bar" data-percentage="100%"></div>
              </div>          
              <div class="description">
                <i class="icon-custom-up"></i>
                <% unless @last_sms.blank? %>
                  <span class="text-white mini-description ">&nbsp; updated <span class="blend"><%= time_ago_in_words(@last_sms.created_at) %> &nbsp;ago</span></span>
                <% end %>
              </div> 
            </div>  
          </div>
        </div>
        
        <div class="span3 ">
          <div class="tiles green added-margin">
            <div class="tiles-body">
              <div class="controller">                
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>                  
              </div>    
              <div class="tiles-title">
                STUDENTS
              </div>  
              <div class="heading">
                <span class="animate-number" data-value="<%= @students.count %>" data-animation-duration="1000">
                <%= @students.count %>
                </span>
              </div>
              <div class="progress transparent progress-white progress-small no-radius">
                <div class="bar animate-progress-bar" data-percentage="100%" ></div>
              </div>        
              <div class="description">
                <i class="icon-custom-up"></i>
                <% unless @last_student.blank? %>
                  <span class="text-white mini-description ">&nbsp; updated <span class="blend"><%= time_ago_in_words(@last_student.created_at) %> &nbsp;ago</span></span>
                <% end %>
              </div>  
            </div>
          </div>
        </div>
    
        <div class="span3 ">
          <div class="tiles red added-margin">
            <div class="tiles-body">
              <div class="controller">                
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>                    
              </div>  
              <div class="tiles-title">
                TEACHING STAFFS
              </div>  
              <div class="heading">
                <span class="animate-number" data-value="<%= @teachers.count %>" data-animation-duration="1200">
                <%= @teachers.count %>
                </span> 
              </div>
              <div class="progress transparent progress-white progress-small no-radius">
                <div class="bar animate-progress-bar" data-percentage="100%" ></div>
              </div>
              <div class="description">
                <i class="icon-custom-up"></i>
                <% unless @last_teacher.blank? %>
                  <span class="text-white mini-description ">&nbsp; updated <span class="blend">
                  <%= time_ago_in_words(@last_teacher.created_at) %> &nbsp;ago</span></span>
                <% end %>
              </div>  
            </div>
          </div>
        </div> 
        
        <div class="span3">
          <div class="tiles purple added-margin">
            <div class="tiles-body">
              <div class="controller">                
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>                  
              </div>    
              <div class="tiles-title">
                NON TEACHING STAFFS
              </div>  
              <div class="row-fluid">
                <div class="heading">
                  <span class="animate-number" data-value="<%= @non_teachers.count %>" data-animation-duration="700">
                  <%= @non_teachers.count %>
                  </span> 
                </div>
                <div class="progress transparent progress-white progress-small no-radius">
                  <div class="bar animate-progress-bar" data-percentage="100%"></div>
                </div>
              </div>
              <div class="description">
                <i class="icon-custom-up"></i>
                <% unless @last_non_teacher.blank? %>
                  <span class="text-white mini-description ">&nbsp; updated <span class="blend">
                    <%= time_ago_in_words(@last_non_teacher.created_at) %> &nbsp;ago
                  </span></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>      
      </div>
    </div> 

    <div class="row-fluid ">      
      <div class="span4">
        <div class="tiles white">
          <div class="tiles-body">
            <div class="controller">                
              <a href="javascript:;" class="reload"></a>
              <a href="javascript:;" class="remove"></a>
            </div>
            <div class="tiles-title">
              BIRTHDAY BABY <strong><%= Date.today.strftime("%d/%m/%Y") %></strong>
            </div>
            </br>
            <% @birthday_name.each_with_index do |birthday_name, index| %>
              <div class="notification-messages info">
                <div class="message-wrapper">
                  <div class="heading">
                    <%= birthday_name %>
                  </div>
                </div>
                <div class="date pull-right">
                  <%= @birthday_role[index] %>
                </div>
              </div>
            <% end %>           
          </div>
        </div>          
      </div>  
      <div class="span4">
        <div class="tiles white">
          <div class="tiles-body">
            <div class="controller">                
              <a href="javascript:;" class="reload"></a>
              <a href="javascript:;" class="remove"></a>                  
            </div>
            <div class="tiles-title">
              JOB ANNIVERSARY <strong><%= Date.today.strftime("%d/%m/%Y") %></strong>
            </div>              
            </br>
            <% @job_anniversary_name.each_with_index do |job_anniversary_name, index| %>
              <div class="notification-messages info">
                <div class="message-wrapper">
                  <div class="heading">
                    <%= job_anniversary_name %>
                  </div>
                </div>
                <div class="date pull-right">
                  <%= @job_anniversary_role[index] %>
                </div>
              </div>
            <% end %>                
          </div>
        </div>          
      </div>  

      <div class="span4">
        <div class="tiles white">
          <div class="tiles-body">
            <div class="controller">                
              <a href="javascript:;" class="reload"></a>
              <a href="javascript:;" class="remove"></a>                  
            </div>
            <div class="tiles-title">
              WEDDING ANNIVERSARY <strong><%= Date.today.strftime("%d/%m/%Y") %></strong>
            </div>              
            </br>
            <% @wedding_anniversary_name.each_with_index do |wedding_anniversary_name, index| %>
              <div class="notification-messages info">
                <div class="message-wrapper">
                  <div class="heading">
                    <%= wedding_anniversary_name %>
                  </div>
                </div>
                <div class="date pull-right">
                  <%= @wedding_anniversary_role[index] %>
                </div>
              </div>
            <% end %>           
          </div>
        </div>          
      </div>  
    </div>
    <div class="clearfix"></div>
    <br/><br/>
    <div class="row-fluid ">      
      <div class="span12">
        <div class="tiles white">
          <div class="tiles-body">
            <div class="controller">                
              <a href="javascript:;" class="reload"></a>
              <a href="javascript:;" class="remove"></a>                  
            </div>
            <div class="tiles-title">
              LATEST NOTIFICATIONS
            </div>              
            </br>
            <% @sms.each do |sms| %>
              <div class="notification-messages info">
                <div class="message-wrapper">
                  <div class="heading">Message : 
                    <%= sms.message %>
                  </div>
                </div>
                <div class="date pull-right">
                  <%= time_ago_in_words(sms.created_at) %>
                </div>
              </div>
            <% end %>        
          </div>
        </div>          
      </div>  
    </div>
  </div>  
<!-- END PAGE --> 
</div>