config/routes.rb
SchoolManagementSystem::Application.routes.draw do
  get "alerts/quick_sms"

  get "alerts/noticeboard"

  resources :non_teaching_staffs

  resources :teaching_staffs

  resources :students

  get "wishes/index"
  get "users/new"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  resources :sessions

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  post "alerts/send_message"
  post "alerts/send_multi_message"

  
  get "home/index"
  get "home/account"
  post "home/user_profile"
  post "home/settings"

  root :to => 'home#index'

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_filter :authenticate

  def quick_sms
  end

  def noticeboard
    @teachers = TeachingStaff.all
    @sections = ('A'..'Z').to_a
    @standards = (1..12).to_a
    @non_teachers = NonTeachingStaff.all
  end

  def send_message
    setting = Settings.first
    waysms = WaySms::SmsSender.new(setting.username, setting.password)
    waysms.send(params[:mobile_number], "#{params[:messages]} - by #{setting.signature}")
    Sms.create(:message => params[:messages])
    flash[:notice] = "Message Send Successfully"
    redirect_to alerts_quick_sms_path
  end

  def send_multi_message
    @teachers = params[:teachers]
    @student_standards = params[:student_standards]
    @student_sections = params[:student_sections]
    @non_teachers = params[:non_teachers]

    mobile_numbers = []
    
    unless @teachers.blank?
      @teachers.each do |teacher|
        teaching_staff = TeachingStaff.find_by_full_name(teacher)
        unless teaching_staff.blank?
          mobile_numbers << teaching_staff.mobile
        end
      end
    end

    unless @student_standards.blank?
      @student_standards.each do |standard|
        student_standard_lists = Student.find_all_by_standard(standard)
        unless student_standard_lists.blank?
          student_standard_lists.each do |student_standard_list|
            mobile_numbers << student_standard_list.phone_number
          end
        end
      end
    end

    unless @student_sections.blank?
      @student_sections.each do |section|
        student_section_lists = Student.find_all_by_standard(section)
        unless student_section_lists.blank?
          student_section_lists.each do |student_section_list|
            mobile_numbers << student_section_list.phone_number
          end
        end
      end
    end

    unless @non_teachers.blank?
      @non_teachers.each do |non_teacher|
        non_teaching_staff = NonTeachingStaff.find_by_full_name(non_teacher)
        unless non_teaching_staff.blank?
          mobile_numbers << non_teaching_staff.mobile
        end
      end
    end
    setting = Settings.first
    waysms = WaySms::SmsSender.new(setting.username, setting.password)
    mobile_numbers.uniq!.each do |mobile_number|  
      waysms.send(mobile_number, "#{params[:messages]} - by #{setting.signature}")
    end
    Sms.create(:message => params[:messages])
    flash[:notice] = "Message Send Successfully"
    redirect_to alerts_noticeboard_path
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/noticeboard.html.erb
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
  <div class="content">
    <div id="container">
      <div class="row-fluid">
        <%= form_tag alerts_send_multi_message_path do %>
          <div class="span10">
            <div class="grid simple">
              <div class="grid-title no-border">
                <h4>Noticeboard</h4>
                <div class="tools"> 
                  <a href="javascript:;" class="collapse"></a>
                  <a href="javascript:;" class="reload"></a>
                </div>
                <hr/>
              </div>
              <div class="grid-body no-border"> <br>
                <div class="row-fluid">
                  <div class="span8">
                    <div class="control-group">
                      <label class="control-label">Teachers</label>
                      <span class="help">e.g. "Teacher X"</span>
                      <div class="controls">
                        <select id="teachers" name="teachers[]" style="width:100%" multiple>
                          <% @teachers.each do |teacher| %>
                            <option value="<%= teacher.full_name %>"><%= teacher.full_name %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Student Standard</label>
                      <span class="help">e.g. "Class 1"</span>
                      <div class="controls">
                        <select id="student_standard" name="student_standards[]" style="width:100%" multiple>
                          <% @standards.each do |standard| %>
                            <option value="<%= standard %>"><%= standard %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Student Section</label>
                      <span class="help">e.g. "Section D"</span>
                      <div class="controls">
                        <select id="student_section" name="student_sections[]" style="width:100%" multiple>
                          <% @sections.each do |section| %>
                            <option value="<%= section %>"><%= section %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Non Teachers</label>
                      <span class="help">e.g. "Driver"</span>
                      <div class="controls">
                        <select id="non_teachers" name="non_teachers[]" style="width:100%" multiple>
                          <% @non_teachers.each do |non_teacher| %>
                            <option value="<%= non_teacher.full_name %>"><%= non_teacher.full_name %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Message</label>
                      <span class="help">e.g. "Hi !!! Good Morning"</span>
                      <div class="controls">
                        <%= text_area_tag :messages, nil, :class=>"span12", :placeholder => "Messages", :rows => "10"  %>
                      </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Send</button>
                    <a href="#" class="btn btn-primary">Clear</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
         <div class="span10">
          <div class="grid simple">
            <div class="grid-title no-border">
              <h4>Message Preview</h4>
              <div class="tools"> 
                <a href="javascript:;" class="collapse"></a>
                <a href="javascript:;" class="reload"></a>
              </div>
              <hr/>
            </div>
            <div class="grid-body no-border"> <br>
              <div class="row-fluid">
                <div class="span8">
                  <div id="preview"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#messages").keyup(function(){
    message = $("#messages").val()
    message = message //+ " - <%#= signature %>"
    $("#preview").html(message);
  });
</script>

app/views/alerts/quick_sms.html.erb
<!-- BEGIN PAGE CONTAINER-->
<div class="page-content">
  <div class="content">
    <div id="container">
      <div class="row-fluid">
        <%= form_tag alerts_send_message_path do %>
          <div class="span10">
            <div class="grid simple">
              <div class="grid-title no-border">
                <h4>Quick SMS</h4>
                <div class="tools"> 
                  <a href="javascript:;" class="collapse"></a>
                  <a href="javascript:;" class="reload"></a>
                </div>
              </div>
              <div class="grid-body no-border"> <br>
                <div class="row-fluid">
                  <div class="span8">
                    <div class="control-group">
                      <label class="control-label">Mobile Number</label>
                      <span class="help">e.g. "987654321"</span>
                      <div class="controls">
                        <input type="text" name="mobile_number" placeholder="987654321" class="span12" />
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Message</label>
                      <span class="help">e.g. "Hi !!! Good Morning"</span>
                      <div class="controls">
                        <%= text_area_tag :messages, nil, :class=>"span12", :placeholder => "Messages", :rows => "10"  %>
                      </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Send</button>
                    <a href="#" class="btn btn-primary">Clear</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
         <div class="span10">
          <div class="grid simple">
            <div class="grid-title no-border">
              <h4>Message Preview</h4>
              <div class="tools"> 
                <a href="javascript:;" class="collapse"></a>
              </div>
              <hr/>
            </div>
            <div class="grid-body no-border"> <br>
              <div class="row-fluid">
                <div class="span8">
                  <div id="preview"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#messages").keyup(function(){
    message = $("#messages").val()
    message = message //+ " - <%#= signature %>"
    $("#preview").html(message);
  });
</script>