config/routes.rb
SchoolManagementSystem::Application.routes.draw do
  get "alerts/quick_sms"

  get "alerts/noticeboard"

  resources :non_teaching_staffs

  resources :teaching_staffs

  resources :students

  get "wishes/index"
  get "users/new"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  resources :sessions

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  post "alerts/send_message"
  post "alerts/send_multi_message"

  
  get "home/index"
  get "home/account"
  post "home/user_profile"
  post "home/settings"

  root :to => 'home#index'

end

app/views/shared/body/_chat.html.erb
<div id="sidr">
  <div class="chat-window-wrapper">
    <div class="chat-header"></div>  
    <div class="side-widget">
      <div class="side-widget-title">
        Welcome <span class="bold"><%= current_user.blank? ? 'Guest' : current_user.username %>
        </span>      
      </div>
      <div class="side-widget-content">
        <div id="groups-list">
          <ul class="groups" >
            <li><a href="/home/account"><div class="status-icon green"></div>My Account</a></li>
            <li><a href="/log_out"><div class="status-icon green"></div>Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/body/_header.html.erb
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse "> 
  <!-- BEGIN TOP NAVIGATION BAR -->
  <div class="navbar-inner">
    <%= render 'shared/body/top_nav' %>   
  </div>
</div>
<!-- END HEADER --> 

app/views/shared/body/_js_files.html.erb
<!-- BEGIN CORE JS FRAMEWORK--> 
  <script src="/plugins/jquery-1.8.3.min.js" type="text/javascript"></script> 
  <script src="/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script> 
  <script src="/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script> 
  <script src="/plugins/breakpoints.js" type="text/javascript"></script> 
  <script src="/plugins/jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script> 
  <script src="/plugins/jquery-datatable/js/jquery.dataTables.min.js" type="text/javascript" ></script>
<script src="/plugins/jquery-datatable/extra/js/TableTools.min.js" type="text/javascript" ></script>
<script type="text/javascript" src="/plugins/datatables-responsive/js/datatables.responsive.js"></script>
<script type="text/javascript" src="/plugins/datatables-responsive/js/lodash.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<script src="/js/datatables.js" type="text/javascript"></script>

<!-- END CORE JS FRAMEWORK --> 

<!--[if lt IE 9]>
  <script src="/plugins/excanvas.js"></script>
  <script src="/plugins/respond.js"></script> 
<![endif]--> 

<!-- BEGIN PAGE LEVEL JS --> 
  <script src="/plugins/pace/pace.min.js" type="text/javascript"></script>  
  <script src="/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script> 
  <script src="/plugins/jquery-numberAnimate/jquery.animateNumbers.js" type="text/javascript"></script> 
  <script src="/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" type="text/javascript"></script>  
  <script src="/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script> 
  <script src="/plugins/jquery-block-ui/jqueryblockui.js" type="text/javascript"></script> 
  <script src="/plugins/bootstrap-select2/select2.min.js" type="text/javascript"></script>
  <script src="/plugins/jquery-ricksaw-chart/js/raphael-min.js"></script> 
  <script src="/plugins/jquery-ricksaw-chart/js/d3.v2.js"></script>
  <script src="/plugins/jquery-ricksaw-chart/js/rickshaw.min.js"></script>
  <script src="/plugins/jquery-morris-chart/js/morris.min.js"></script>
  <script src="/plugins/jquery-easy-pie-chart/js/jquery.easypiechart.min.js"></script>
  <script src="/plugins/jquery-slider/jquery.sidr.min.js" type="text/javascript"></script>  
  <script src="/plugins/jquery-jvectormap/js/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>   
  <script src="/plugins/jquery-jvectormap/js/jquery-jvectormap-us-lcc-en.js" type="text/javascript"></script>   
  <script src="/plugins/jquery-sparkline/jquery-sparkline.js"></script>
  <script src="/plugins/jquery-flot/jquery.flot.min.js"></script>
  <script src="/plugins/jquery-flot/jquery.flot.animator.min.js"></script>
  <!-- <script src="/plugins/skycons/skycons.js"></script> -->
<!-- END PAGE LEVEL PLUGINS -->   

<!-- PAGE JS -->
  <% if (params[:controller] =='home') %>
  <!--  <script src="/js/dashboard.js" type="text/javascript"></script> -->
  <% else %>
    <script src="/js/form_elements.js" type="text/javascript"></script> 
  <% end %>
<!-- END PAGE JS -->

<!-- BEGIN CORE TEMPLATE JS --> 
  <script src="/js/core.js" type="text/javascript"></script> 
  <script src="/js/demo.js" type="text/javascript"></script> 
<!-- END CORE TEMPLATE JS -->

app/views/shared/body/_sidebar.html.erb
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar" id="main-menu">     
  <!-- BEGIN SIDEBAR MENU -->  
  <p class="menu-title">BROWSE <span class="pull-right"><a href="javascript:;"><i class="icon-refresh"></i></a></span></p>
  <ul>  
    <li class="start <%= 'active' if (params[:controller] == 'home' && params[:action] == 'index')%>">
      <a href="/">
        <i class="icon-custom-home"></i>
        <span class="title">Dashboard</span>
        <span class="selected"></span>
      </a>
    </li>
    <li class="<%= 'active' if (params[:controller] == 'students' && params[:action] == 'new' || 
                                 params[:controller] == 'students' && params[:action] == 'index')%>">
      <a href="javascript:;">
        <i class="icon-custom-ui"></i>
        <span class="title">Students</span>
        <span class="arrow "></span>
      </a>
      <ul class="sub-menu">
        <li class="<%= 'active' if (params[:controller] == 'students' && params[:action] == 'new') %>"> <a href="<%= new_student_path %>"> Add Student </a> </li>
        <li class="<%= 'active' if (params[:controller] == 'students' && params[:action] == 'index') %>"> <a href="<%= students_path %>"> List Students </a> </li>
      </ul>
    </li>
    <li class="<%= 'active' if (params[:controller] == 'teaching_staffs' && params[:action] == 'new' || 
                                 params[:controller] == 'teaching_staffs' && params[:action] == 'index')%>"> 
      <a href="javascript:;"> 
        <i class="icon-custom-form"></i> 
        <span class="title">Teachers</span> 
        <span class="arrow "></span>
      </a>
      <ul class="sub-menu">
        <li class="<%= 'active' if (params[:controller] == 'teaching_staffs' && params[:action] == 'new') %>"><a href="<%= new_teaching_staff_path %>">Add Teacher</a> </li>
        <li class="<%= 'active' if (params[:controller] == 'teaching_staffs' && params[:action] == 'index') %>"><a href="<%= teaching_staffs_path %>">List Teachers</a> </li>
      </ul>
    </li>
    <li class="<%= 'active' if (params[:controller] == 'non_teaching_staffs' && params[:action] == 'new' || 
                                 params[:controller] == 'non_teaching_staffs' && params[:action] == 'index')%>">
      <a href="javascript:;"> 
        <i class="icon-custom-portlets"></i> 
        <span class="title">Non Teaching Staffs</span> 
        <span class="arrow "></span>
      </a>
      <ul class="sub-menu">
        <li class="<%= 'active' if (params[:controller] == 'non_teaching_staffs' && params[:action] == 'new') %>"> <a href="<%= new_non_teaching_staff_path %>">Add Non Teaching Staff</a> </li>
        <li class="<%= 'active' if (params[:controller] == 'non_teaching_staffs' && params[:action] == 'index') %>"> <a href="<%= non_teaching_staffs_path %>">List Non Teaching Staffs</a> </li>
      </ul>
    </li>
    <li class="<%= 'active' if (params[:controller] == 'alerts' && params[:action] == 'quick_sms' || 
                                 params[:controller] == 'alerts' && params[:action] == 'noticeboard')%>"> 
      <a href="javascript:;">
        <i class="icon-custom-thumb"></i>
        <span class="title">Alerts</span>
        <span class="arrow "></span> 
      </a>
      <ul class="sub-menu">
        <li class="<%= 'active' if (params[:controller] == 'alerts' && params[:action] == 'quick_sms') %>"> <a href="<%= alerts_quick_sms_path %>"> Quick SMS </a> </li>
        <li  class="<%= 'active' if (params[:controller] == 'alerts' && params[:action] == 'noticeboard') %>"> <a href="<%= alerts_noticeboard_path %>"> Noticeboard </a> </li>
      </ul>
    </li>
  </ul>

  <a href="#" class="scrollup">Scroll</a>
  <div class="clearfix"></div>
  <!-- END SIDEBAR MENU --> 
</div>

app/views/shared/body/_top_nav.html.erb
<div class="header-seperation"> 
  <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">  
    <li class="dropdown">
      <a id="main-menu-toggle" href="#main-menu"  class="" > 
        <div class="iconset top-menu-toggle-white"></div>
      </a>
    </li>     
  </ul>
  
  <!-- BEGIN LOGO --> 
  <a href="/">
    <img src="/img/logo.png" class="logo pull-left"  data-src="/img/logo.png" data-src-retina="/img/logo2x.png" width="106" height="92"/>
  </a>
  <!-- END LOGO --> 
  
  <ul class="nav pull-right notifcation-center">  
    <li class="dropdown" id="header_task_bar">
      <a href="/" class="dropdown-toggle active" data-toggle="">
        <div class="iconset top-home"></div>
      </a>
    </li>
    <li class="dropdown" id="portrait-chat-toggler" style="display:none"> 
      <a href="#sidr" class="chat-menu-toggle">
        <div class="iconset top-chat-white "></div>
      </a>
    </li>        
  </ul>
</div>
<!-- END RESPONSIVE MENU TOGGLER --> 
<div class="header-quick-nav" > 
  <!-- BEGIN TOP NAVIGATION MENU -->
  <div class="pull-left"> 
    <ul class="nav quick-section">
      <li class="quicklinks">
        <a href="#" class="" id="layout-condensed-toggle" >
          <div class="iconset top-menu-toggle-dark"></div>
        </a>
      </li>        
    </ul>
    <ul class="nav quick-section">
      <li class="quicklinks">
        <a href="#" class="" >
          <div class="iconset top-reload"></div>
        </a>
      </li>
    </ul>
  </div>
  <!-- END TOP NAVIGATION MENU -->
  <!-- BEGIN CHAT TOGGLER -->
  <div class="pull-right"> 
    <div class="chat-toggler">  
      <a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom" 
         data-content='' data-toggle="dropdown" data-original-title="">
        <div class="profile-pic"> 
          <img alt="" src="/img/profiles/avatar.png" data-src="/img/profiles/avatar.png" data-src-retina="/img/profiles/avatar.png" width="35" height="35" /> 
        </div>            
          <div class="iconset top-down"></div>
          <div class="user-details"> 
            <div class="username">
              Welcome <span class="bold"><%= current_user.blank? ? 'Guest' : current_user.username %></span>                  
            </div>            
          </div> 
        </a>            
      </div>
      <ul class="nav quick-section ">
        <li class="quicklinks"> 
          <a data-toggle="dropdown" class="dropdown-toggle  pull-right" href="#">           
            <div class="iconset top-settings-dark "></div>  
          </a>
          <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="dropdownMenu">
            <li><a href="/home/account"> My Account</a></li>
            <li class="divider"></li>                
            <li><a href="/log_out"><i class="icon-off"></i>&nbsp;&nbsp;Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END CHAT TOGGLER -->
  </div> 
  <!-- END TOP NAVIGATION MENU --> 
</div>
<!-- END TOP NAVIGATION BAR --> 